# netlify.toml

[build]
  publish = "."                     # your static site root
  functions = "netlify/functions"   # path to serverless functions
  command = "npm run build"         # optional (you can remove if no build step)

[dev]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"          # modern bundler
  external_node_modules = [
    "@supabase/supabase-js",
    "midtrans-client",
    "bcryptjs"
  ]

[functions.environment]
  NODE_VERSION = "20"
