[build]
  publish = "public"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**"]
  external_node_modules = [
    "@supabase/supabase-js",
    "midtrans-client",
    "bcryptjs",
    "dotenv"
  ]

  # ✅ Declare ESM format the correct way (as object)
  [functions.format]
  esm = true

  # ✅ Node bundler ES module exception (for midtrans-client)
  [functions.node_bundler_es_modules]
  external_node_modules = [
    "midtrans-client"
  ]

[functions.environment]
  NODE_VERSION = "20"
