[build]
  publish = "public"                 # <-- serve files from public/
  functions = "netlify/functions"    # serverless functions folder

[dev]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "@supabase/supabase-js",
    "midtrans-client",
    "bcryptjs"
  ]

[functions.environment]
  NODE_VERSION = "20"
